import type {
  GeneratorTemplate,
  TemplateCategory,
  TemplateId,
} from "@/lib/generator/types";

export const DEFAULT_GENERATOR_TEMPLATE_ID: TemplateId = "center-mono";

export const GENERATOR_TEMPLATE_CATEGORIES: readonly {
  id: "all" | TemplateCategory;
  label: string;
}[] = [
  { id: "all", label: "All" },
  { id: "editing", label: "Editing" },
  { id: "streaming", label: "Streaming" },
  { id: "social", label: "Social" },
  { id: "events", label: "Events" },
  { id: "fitness", label: "Fitness" },
  { id: "cinematic", label: "Cinematic" },
  { id: "minimal", label: "Minimal" },
] as const;

export const GENERATOR_QUICK_TEMPLATE_IDS: readonly TemplateId[] = [
  "clean-corner",
  "center-mono",
  "obs-starting-soon",
  "twitch-neon",
  "capcut-portrait",
  "launch-countdown",
] as const;

export const GENERATOR_TEMPLATES = [
  {
    id: "clean-corner",
    name: "Clean Corner",
    tier: "free",
    category: "editing",
    useCase: "Tutorials and screen recordings",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "minimal",
    sampleTime: "0:30",
    visual: {
      motif: "corner-plate",
      accent: "#00D4FF",
      secondaryAccent: "#00FF88",
      surfaceColor: "#090B10",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-720" },
      textStyle: { fontSize: 72, textColor: "#F8FAFC" },
      placement: { anchor: "top-right", offsetX: -28, offsetY: 28 },
    },
  },
  {
    id: "broadcast-lower-third",
    name: "Broadcast Lower Third",
    tier: "free",
    category: "editing",
    useCase: "Lower thirds and broadcast footage",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "classic",
    sampleTime: "00:30",
    visual: {
      motif: "lower-third",
      accent: "#00FF88",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#090B10",
      kicker: "COUNTDOWN",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 76, strokeWidth: 3 },
      placement: { anchor: "bottom-left", offsetX: 36, offsetY: -36 },
    },
  },
  {
    id: "center-mono",
    name: "Center Mono",
    tier: "free",
    category: "minimal",
    useCase: "A dependable timer for any video",
    orientation: "all",
    recommendedFormat: "png-sequence",
    themePresetId: "cyber",
    sampleTime: "0:30",
    visual: {
      motif: "none",
      accent: "#00D4FF",
      secondaryAccent: "#00FF88",
      surfaceColor: "#090B10",
    },
    settings: {
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "high-contrast-classic",
    name: "High Contrast Classic",
    tier: "free",
    category: "editing",
    useCase: "Noisy footage and bright backgrounds",
    orientation: "all",
    recommendedFormat: "png-sequence",
    themePresetId: "classic",
    sampleTime: "00:30",
    visual: {
      motif: "center-plate",
      accent: "#FFB83E",
      secondaryAccent: "#F8FAFC",
      surfaceColor: "#080A0E",
    },
    settings: {
      textStyle: {
        fontSize: 98,
        textColor: "#FFFFFF",
        strokeWidth: 7,
        strokeColor: "#05070A",
      },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "quiet-tutorial",
    name: "Quiet Tutorial",
    tier: "free",
    category: "minimal",
    useCase: "Courses, demos, and walkthroughs",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "minimal",
    sampleTime: "0:30",
    visual: {
      motif: "corner-plate",
      accent: "#00FF88",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#0B0D12",
    },
    settings: {
      textStyle: { fontSize: 64, textColor: "#E8EDF5", shadowBlur: 8 },
      placement: { anchor: "bottom-right", offsetX: -30, offsetY: -30 },
    },
  },
  {
    id: "webinar-slate",
    name: "Webinar Slate",
    tier: "free",
    category: "events",
    useCase: "Webinar waiting rooms",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "minimal",
    sampleTime: "05:00",
    visual: {
      motif: "slate",
      accent: "#3B7BFF",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#0A1020",
      kicker: "WEBINAR STARTS IN",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 90, fontWeight: 700 },
      placement: { anchor: "center", offsetX: 0, offsetY: 18 },
    },
  },
  {
    id: "obs-starting-soon",
    name: "OBS Starting Soon",
    tier: "free",
    category: "streaming",
    useCase: "OBS starting scenes",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "cyber",
    sampleTime: "10:00",
    visual: {
      motif: "stream-frame",
      accent: "#00FF88",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#070B0D",
      kicker: "STARTING SOON",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 92, glowColor: "rgba(0, 255, 136, 0.52)" },
      placement: { anchor: "center", offsetX: 0, offsetY: 12 },
    },
  },
  {
    id: "obs-break-timer",
    name: "OBS Break Timer",
    tier: "free",
    category: "streaming",
    useCase: "Stream break screens",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "classic",
    sampleTime: "05:00",
    visual: {
      motif: "stream-frame",
      accent: "#FFB83E",
      secondaryAccent: "#FF5C8A",
      surfaceColor: "#100D08",
      kicker: "BE RIGHT BACK",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 90, textColor: "#FFF1D6", strokeWidth: 4 },
      placement: { anchor: "center", offsetX: 0, offsetY: 12 },
    },
  },
  {
    id: "twitch-neon",
    name: "Twitch Neon",
    tier: "free",
    category: "streaming",
    useCase: "Twitch streams and nightlife content",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "neon",
    sampleTime: "03:00",
    visual: {
      motif: "neon-lines",
      accent: "#F02EBD",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#0E0712",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "premiere-safe-text",
    name: "Premiere Safe Text",
    tier: "free",
    category: "editing",
    useCase: "Premiere Pro overlays",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "minimal",
    sampleTime: "0:30",
    visual: {
      motif: "editor-safe",
      accent: "#00D4FF",
      secondaryAccent: "#3B7BFF",
      surfaceColor: "#090B10",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      placement: { anchor: "bottom-right", offsetX: -44, offsetY: -42 },
    },
  },
  {
    id: "davinci-clean",
    name: "DaVinci Clean",
    tier: "free",
    category: "editing",
    useCase: "DaVinci Resolve overlays",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "minimal",
    sampleTime: "00:30",
    visual: {
      motif: "editor-safe",
      accent: "#FF6B2C",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#0D0A08",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { textColor: "#FFF0E8", strokeColor: "rgba(35, 12, 4, 0.75)" },
      placement: { anchor: "bottom-left", offsetX: 44, offsetY: -42 },
    },
  },
  {
    id: "capcut-portrait",
    name: "CapCut Portrait",
    tier: "free",
    category: "social",
    useCase: "CapCut vertical edits",
    orientation: "portrait",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "classic",
    sampleTime: "15",
    visual: {
      motif: "portrait-frame",
      accent: "#F02EBD",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#0C0810",
    },
    settings: {
      timer: { displayFormat: "ss" },
      canvas: { resolutionPresetId: "portrait-1080" },
      textStyle: { fontSize: 118, strokeWidth: 5 },
      placement: { anchor: "center", offsetX: 0, offsetY: -60 },
    },
  },
  {
    id: "reels-bold-center",
    name: "Reels Bold Center",
    tier: "free",
    category: "social",
    useCase: "Reels and Shorts",
    orientation: "portrait",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "retro",
    sampleTime: "05",
    visual: {
      motif: "social-burst",
      accent: "#FFB83E",
      secondaryAccent: "#F02EBD",
      surfaceColor: "#110A10",
    },
    settings: {
      timer: { displayFormat: "ss" },
      canvas: { resolutionPresetId: "portrait-1080" },
      textStyle: { fontSize: 132 },
      placement: { anchor: "center", offsetX: 0, offsetY: -40 },
    },
  },
  {
    id: "square-social",
    name: "Square Social",
    tier: "free",
    category: "social",
    useCase: "Square feeds and posts",
    orientation: "square",
    recommendedFormat: "png-sequence",
    themePresetId: "cyber",
    sampleTime: "0:10",
    visual: {
      motif: "social-burst",
      accent: "#00D4FF",
      secondaryAccent: "#A3FA38",
      surfaceColor: "#071013",
    },
    settings: {
      canvas: { resolutionPresetId: "square-1080" },
      textStyle: { fontSize: 106 },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "simple-workout",
    name: "Simple Workout",
    tier: "free",
    category: "fitness",
    useCase: "Workout sets and circuits",
    orientation: "all",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "classic",
    sampleTime: "00:45",
    visual: {
      motif: "scoreboard",
      accent: "#A3FA38",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#071006",
      kicker: "WORK",
    },
    settings: {
      textStyle: { fontSize: 108, textColor: "#F5FFE8", strokeWidth: 4 },
      placement: { anchor: "center", offsetX: 0, offsetY: 18 },
    },
  },
  {
    id: "classroom-timer",
    name: "Classroom Timer",
    tier: "free",
    category: "events",
    useCase: "Classrooms and lessons",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "minimal",
    sampleTime: "02:00",
    visual: {
      motif: "slate",
      accent: "#00FF88",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#07110D",
      kicker: "ACTIVITY TIMER",
    },
    settings: {
      textStyle: { fontSize: 88, fontWeight: 700 },
      placement: { anchor: "center", offsetX: 0, offsetY: 18 },
    },
  },
  {
    id: "event-lobby",
    name: "Event Lobby",
    tier: "free",
    category: "events",
    useCase: "Event waiting rooms",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "glow",
    sampleTime: "15:00",
    visual: {
      motif: "slate",
      accent: "#FFB83E",
      secondaryAccent: "#F8FAFC",
      surfaceColor: "#100D08",
      kicker: "EVENT BEGINS IN",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 96 },
      placement: { anchor: "center", offsetX: 0, offsetY: 20 },
    },
  },
  {
    id: "transparent-minimal",
    name: "Transparent Minimal",
    tier: "free",
    category: "minimal",
    useCase: "Clean transparent overlays",
    orientation: "all",
    recommendedFormat: "png-sequence",
    themePresetId: "minimal",
    sampleTime: "0:30",
    visual: {
      motif: "none",
      accent: "#00FF88",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#090B10",
    },
    settings: {
      canvas: { backgroundMode: "transparent" },
      textStyle: { fontSize: 78, strokeWidth: 1 },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "cinematic-warm-glow",
    name: "Cinematic Warm Glow",
    tier: "growth",
    category: "cinematic",
    useCase: "Lifestyle intros and trailers",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "glow",
    sampleTime: "00:30",
    visual: {
      motif: "film",
      accent: "#FFB83E",
      secondaryAccent: "#FFF2D6",
      surfaceColor: "#15110B",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 92, textColor: "#FFF2D6" },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "film-leader",
    name: "Film Leader",
    tier: "growth",
    category: "cinematic",
    useCase: "Trailer and film countdowns",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "mono",
    sampleTime: "08",
    visual: {
      motif: "film",
      accent: "#F2E5C7",
      secondaryAccent: "#8D8067",
      surfaceColor: "#15130F",
      kicker: "PICTURE START",
    },
    settings: {
      timer: { displayFormat: "ss" },
      textStyle: { fontSize: 128, textColor: "#F2E5C7", letterSpacing: 0.12 },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "launch-countdown",
    name: "Launch Countdown",
    tier: "growth",
    category: "events",
    useCase: "Product launches",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "classic",
    sampleTime: "01:00",
    visual: {
      motif: "slate",
      accent: "#FF4A58",
      secondaryAccent: "#FFB83E",
      surfaceColor: "#130709",
      kicker: "LAUNCH IN",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 104, textColor: "#FFF0F1" },
      placement: { anchor: "center", offsetX: 0, offsetY: 18 },
    },
  },
  {
    id: "glass-center-pill",
    name: "Glass Center Pill",
    tier: "growth",
    category: "minimal",
    useCase: "Clean branded video",
    orientation: "all",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "glass",
    sampleTime: "0:30",
    visual: {
      motif: "glass",
      accent: "#00D4FF",
      secondaryAccent: "#FFFFFF",
      surfaceColor: "#0A0D13",
    },
    settings: {
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "retro-80s",
    name: "Retro 80s",
    tier: "growth",
    category: "cinematic",
    useCase: "Synthwave content",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "retro",
    sampleTime: "00:30",
    visual: {
      motif: "neon-lines",
      accent: "#F02EBD",
      secondaryAccent: "#FFB83E",
      surfaceColor: "#100718",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "arcade-neon",
    name: "Arcade Neon",
    tier: "growth",
    category: "streaming",
    useCase: "Arcade and game streams",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "scanline",
    sampleTime: "03:00",
    visual: {
      motif: "neon-lines",
      accent: "#A3FA38",
      secondaryAccent: "#F02EBD",
      surfaceColor: "#080D08",
    },
    settings: {
      textStyle: {
        textColor: "#D9FF9C",
        glowColor: "rgba(163, 250, 56, 0.72)",
      },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "crt-scanline",
    name: "CRT Scanline",
    tier: "growth",
    category: "streaming",
    useCase: "Retro streams and analog edits",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "scanline",
    sampleTime: "00:30",
    visual: {
      motif: "scanline",
      accent: "#00FF88",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#061009",
      kicker: "SIGNAL 01",
    },
    settings: {
      textStyle: { fontSize: 92, textColor: "#7CFFB2" },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "sports-scoreboard",
    name: "Sports Scoreboard",
    tier: "growth",
    category: "fitness",
    useCase: "Sports content and match opens",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "classic",
    sampleTime: "12:00",
    visual: {
      motif: "scoreboard",
      accent: "#FF4A58",
      secondaryAccent: "#3B7BFF",
      surfaceColor: "#100709",
      kicker: "GAME START",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 104, textColor: "#FFFFFF" },
      placement: { anchor: "center", offsetX: 0, offsetY: 18 },
    },
  },
  {
    id: "hiit-round-timer",
    name: "HIIT Round Timer",
    tier: "growth",
    category: "fitness",
    useCase: "HIIT intervals and vertical workouts",
    orientation: "portrait",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "classic",
    sampleTime: "00:20",
    visual: {
      motif: "scoreboard",
      accent: "#FF6B2C",
      secondaryAccent: "#FFB83E",
      surfaceColor: "#130A06",
      kicker: "ROUND 03",
    },
    settings: {
      canvas: { resolutionPresetId: "portrait-1080" },
      textStyle: { fontSize: 124, textColor: "#FFF2E8" },
      placement: { anchor: "center", offsetX: 0, offsetY: -60 },
    },
  },
  {
    id: "pomodoro-creator",
    name: "Pomodoro Creator",
    tier: "growth",
    category: "events",
    useCase: "Focus streams and study sessions",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "minimal",
    sampleTime: "25:00",
    visual: {
      motif: "slate",
      accent: "#FF4A58",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#12090B",
      kicker: "FOCUS",
    },
    settings: {
      textStyle: { fontSize: 94, fontWeight: 700 },
      placement: { anchor: "center", offsetX: 0, offsetY: 18 },
    },
  },
  {
    id: "podcast-break",
    name: "Podcast Break",
    tier: "growth",
    category: "events",
    useCase: "Podcast intermissions",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "glass",
    sampleTime: "02:00",
    visual: {
      motif: "lower-third",
      accent: "#7A52F4",
      secondaryAccent: "#F02EBD",
      surfaceColor: "#0C0914",
      kicker: "BACK SHORTLY",
    },
    settings: {
      textStyle: { fontSize: 82, glowColor: "rgba(122, 82, 244, 0.36)" },
      placement: { anchor: "bottom-center", offsetX: 0, offsetY: -38 },
    },
  },
  {
    id: "livestream-intermission",
    name: "Livestream Intermission",
    tier: "growth",
    category: "streaming",
    useCase: "Livestream intermission scenes",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "cyber",
    sampleTime: "07:00",
    visual: {
      motif: "stream-frame",
      accent: "#3B7BFF",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#070B15",
      kicker: "INTERMISSION",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { glowColor: "rgba(59, 123, 255, 0.48)" },
      placement: { anchor: "center", offsetX: 0, offsetY: 12 },
    },
  },
  {
    id: "youtube-premiere",
    name: "YouTube Premiere",
    tier: "growth",
    category: "streaming",
    useCase: "Premieres and scheduled streams",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "classic",
    sampleTime: "02:00",
    visual: {
      motif: "stream-frame",
      accent: "#FF4A58",
      secondaryAccent: "#FFFFFF",
      surfaceColor: "#120708",
      kicker: "PREMIERE STARTS",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 94, textColor: "#FFFFFF" },
      placement: { anchor: "center", offsetX: 0, offsetY: 12 },
    },
  },
  {
    id: "webinar-dark-pro",
    name: "Webinar Dark Pro",
    tier: "growth",
    category: "events",
    useCase: "Professional webinars",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "glass",
    sampleTime: "10:00",
    visual: {
      motif: "slate",
      accent: "#00D4FF",
      secondaryAccent: "#3B7BFF",
      surfaceColor: "#080D16",
      kicker: "SESSION OPENS",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-1080" },
      textStyle: { fontSize: 90 },
      placement: { anchor: "center", offsetX: 0, offsetY: 18 },
    },
  },
  {
    id: "gaming-hud",
    name: "Gaming HUD",
    tier: "growth",
    category: "streaming",
    useCase: "Gaming overlays",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "cyber",
    sampleTime: "03:00",
    visual: {
      motif: "hud",
      accent: "#00D4FF",
      secondaryAccent: "#00FF88",
      surfaceColor: "#050B0F",
      kicker: "TIMER / 01",
    },
    settings: {
      textStyle: { fontSize: 96 },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "creator-brandable",
    name: "Creator Brandable",
    tier: "growth",
    category: "minimal",
    useCase: "Brand-color customization",
    orientation: "all",
    recommendedFormat: "png-sequence",
    themePresetId: "glass",
    sampleTime: "0:30",
    visual: {
      motif: "glass",
      accent: "#00FF88",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#07110D",
      kicker: "YOUR BRAND",
    },
    settings: {
      textStyle: { textColor: "#F4FFF9", glowColor: "rgba(0, 255, 136, 0.24)" },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "lower-corner-glow",
    name: "Lower Corner Glow",
    tier: "growth",
    category: "editing",
    useCase: "Subtle video corners",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "glow",
    sampleTime: "00:30",
    visual: {
      motif: "lower-third",
      accent: "#00D4FF",
      secondaryAccent: "#FFF2D6",
      surfaceColor: "#081014",
    },
    settings: {
      textStyle: {
        fontSize: 72,
        textColor: "#EAFBFF",
        glowColor: "rgba(0, 212, 255, 0.44)",
      },
      placement: { anchor: "bottom-right", offsetX: -36, offsetY: -36 },
    },
  },
  {
    id: "vertical-stream",
    name: "Vertical Stream",
    tier: "growth",
    category: "streaming",
    useCase: "Vertical live streams",
    orientation: "portrait",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "neon",
    sampleTime: "05:00",
    visual: {
      motif: "portrait-frame",
      accent: "#F02EBD",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#0E0712",
      kicker: "LIVE SOON",
    },
    settings: {
      canvas: { resolutionPresetId: "portrait-1080" },
      textStyle: { fontSize: 118 },
      placement: { anchor: "center", offsetX: 0, offsetY: -60 },
    },
  },
  {
    id: "prores-master-look",
    name: "ProRes Master Look",
    tier: "signature",
    category: "editing",
    useCase: "Master-grade editor handoff",
    orientation: "landscape",
    recommendedFormat: "mov-hevc-alpha",
    themePresetId: "classic",
    sampleTime: "00:30",
    visual: {
      motif: "editor-safe",
      accent: "#FFB83E",
      secondaryAccent: "#F8FAFC",
      surfaceColor: "#0D0B07",
      kicker: "MASTER",
    },
    settings: {
      canvas: { resolutionPresetId: "landscape-2160" },
      textStyle: { fontSize: 96, textColor: "#FFF6E6", strokeWidth: 4 },
      placement: { anchor: "bottom-center", offsetX: 0, offsetY: -48 },
    },
  },
  {
    id: "alpha-smoke-reveal",
    name: "Alpha Smoke Reveal",
    tier: "signature",
    category: "cinematic",
    useCase: "Atmospheric intros",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "glow",
    sampleTime: "00:10",
    visual: {
      motif: "smoke",
      accent: "#7A52F4",
      secondaryAccent: "#D5C9FF",
      surfaceColor: "#0C0914",
    },
    settings: {
      textStyle: {
        fontSize: 94,
        textColor: "#EEE9FF",
        glowColor: "rgba(122, 82, 244, 0.52)",
      },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "kinetic-digits",
    name: "Kinetic Digits",
    tier: "signature",
    category: "social",
    useCase: "Fast, dynamic Shorts",
    orientation: "portrait",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "retro",
    sampleTime: "03",
    visual: {
      motif: "social-burst",
      accent: "#FF4A58",
      secondaryAccent: "#FFB83E",
      surfaceColor: "#140809",
    },
    settings: {
      timer: { displayFormat: "ss" },
      canvas: { resolutionPresetId: "portrait-1080" },
      textStyle: { fontSize: 142, shadowOffsetX: 10, shadowOffsetY: 8 },
      placement: { anchor: "center", offsetX: 0, offsetY: -40 },
    },
  },
  {
    id: "audio-tick-sync",
    name: "Audio Tick Sync",
    tier: "signature",
    category: "editing",
    useCase: "Tick-synced edits",
    orientation: "all",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "cyber",
    sampleTime: "0:10",
    visual: {
      motif: "center-plate",
      accent: "#A3FA38",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#071006",
      kicker: "AUDIO SYNC",
    },
    settings: {
      textStyle: {
        textColor: "#E9FFC9",
        glowColor: "rgba(163, 250, 56, 0.5)",
      },
      audio: { variant: "tick-and-beep" },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "split-shadow-pop",
    name: "Split Shadow Pop",
    tier: "signature",
    category: "social",
    useCase: "High-energy pop edits",
    orientation: "all",
    recommendedFormat: "png-sequence",
    themePresetId: "retro",
    sampleTime: "05",
    visual: {
      motif: "social-burst",
      accent: "#F02EBD",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#120812",
    },
    settings: {
      timer: { displayFormat: "ss" },
      textStyle: {
        fontSize: 126,
        textColor: "#FFCE54",
        shadowColor: "#00D4FF",
        shadowOffsetX: 8,
        shadowOffsetY: 8,
      },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "soft-neumorphic",
    name: "Soft Neumorphic",
    tier: "signature",
    category: "minimal",
    useCase: "Soft UI and product video",
    orientation: "all",
    recommendedFormat: "png-sequence",
    themePresetId: "neumorphic",
    sampleTime: "0:30",
    visual: {
      motif: "neumorphic",
      accent: "#D7DEE9",
      secondaryAccent: "#8F9FBC",
      surfaceColor: "#1F2330",
    },
    settings: {
      canvas: { backgroundMode: "solid", backgroundColor: "#1F2330" },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "minimal-caption-safe",
    name: "Minimal Caption Safe",
    tier: "signature",
    category: "editing",
    useCase: "Caption-safe video overlays",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "minimal",
    sampleTime: "0:30",
    visual: {
      motif: "editor-safe",
      accent: "#00FF88",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#07110D",
      kicker: "CAPTION SAFE",
    },
    settings: {
      textStyle: { fontSize: 72 },
      placement: { anchor: "top-right", offsetX: -42, offsetY: 42 },
    },
  },
  {
    id: "tactical-hud",
    name: "Tactical HUD",
    tier: "signature",
    category: "streaming",
    useCase: "Technical and tactical streams",
    orientation: "landscape",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "scanline",
    sampleTime: "03:00",
    visual: {
      motif: "hud",
      accent: "#A3FA38",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#050D07",
      kicker: "T-MINUS",
    },
    settings: {
      textStyle: {
        textColor: "#D9FF9C",
        glowColor: "rgba(163, 250, 56, 0.54)",
      },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "music-visual-timer",
    name: "Music Visual Timer",
    tier: "signature",
    category: "social",
    useCase: "Music countdowns",
    orientation: "square",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "neon",
    sampleTime: "00:30",
    visual: {
      motif: "waveform",
      accent: "#F02EBD",
      secondaryAccent: "#00D4FF",
      surfaceColor: "#0E0712",
    },
    settings: {
      canvas: { resolutionPresetId: "square-1080" },
      textStyle: { fontSize: 92 },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "countdown-ring",
    name: "Countdown Ring",
    tier: "signature",
    category: "events",
    useCase: "Universal event countdowns",
    orientation: "all",
    recommendedFormat: "webm-vp9-alpha",
    themePresetId: "cyber",
    sampleTime: "0:30",
    visual: {
      motif: "ring",
      accent: "#00D4FF",
      secondaryAccent: "#00FF88",
      surfaceColor: "#071014",
    },
    settings: {
      textStyle: { fontSize: 76 },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: "luxury-event",
    name: "Luxury Event",
    tier: "signature",
    category: "events",
    useCase: "Premium event opens",
    orientation: "landscape",
    recommendedFormat: "png-sequence",
    themePresetId: "glow",
    sampleTime: "05:00",
    visual: {
      motif: "slate",
      accent: "#D9B66F",
      secondaryAccent: "#FFF1C9",
      surfaceColor: "#171107",
      kicker: "PRIVATE EVENT",
    },
    settings: {
      canvas: { backgroundMode: "solid", backgroundColor: "#171107" },
      textStyle: {
        fontSize: 90,
        textColor: "#FFF1C9",
        letterSpacing: 0.08,
        glowColor: "rgba(217, 182, 111, 0.34)",
      },
      placement: { anchor: "center", offsetX: 0, offsetY: 18 },
    },
  },
  {
    id: "custom-font-showcase",
    name: "Custom Font Showcase",
    tier: "signature",
    category: "editing",
    useCase: "Custom-font brand treatments",
    orientation: "all",
    recommendedFormat: "png-sequence",
    themePresetId: "glass",
    sampleTime: "0:30",
    visual: {
      motif: "center-plate",
      accent: "#7A52F4",
      secondaryAccent: "#F02EBD",
      surfaceColor: "#0C0914",
      kicker: "CUSTOM TYPE",
    },
    settings: {
      textStyle: {
        fontSize: 96,
        textColor: "#F4EEFF",
        glowColor: "rgba(122, 82, 244, 0.34)",
      },
      placement: { anchor: "center", offsetX: 0, offsetY: 0 },
    },
  },
] as const satisfies readonly GeneratorTemplate[];

export function getGeneratorTemplateById(
  templateId: string | null | undefined,
): GeneratorTemplate {
  return (
    GENERATOR_TEMPLATES.find((template) => template.id === templateId) ??
    GENERATOR_TEMPLATES.find(
      (template) => template.id === DEFAULT_GENERATOR_TEMPLATE_ID,
    ) ??
    GENERATOR_TEMPLATES[0]
  );
}

export function getDefaultTemplateForPreset(presetId: string): GeneratorTemplate {
  return (
    GENERATOR_TEMPLATES.find((template) => template.themePresetId === presetId) ??
    getGeneratorTemplateById(DEFAULT_GENERATOR_TEMPLATE_ID)
  );
}
